### ISSUE TITLE
Enhancement - Support cover entities

### ISSUE THREAD

**Issue by PurelyNicole** [hasscontrol/hasscontrol#15]
Thanks for taking the time to make this widget! It works very well. My issue is very similar to the one reported in #10. But instead of lock, the entity type is [cover](https://developers.home-assistant.io/docs/core/entity/cover). This would allow me to open the Garage Door from the widget.

**Comment by karlenek** [comment]
Sorry for being late in reply! I will investigate further into covers and probably add some simple implementation. After having a quick look it seems like there is a few different variants and scenarios I would need to handle, depending on what type of cover it is and how the cover should be opened/closed. I might do something simple like supporting opening and closing but not tilting etc. Would that suffice?

**Comment by pniewiadowski** [comment]
@karlenek as for me, opening and closing is totally fine! Thanks.

**Comment by rforro** [comment]
The complication is that cover supports more than one "mode." The are:

- **simple open/close** This should be easy, it's basically like a power switch with 2 states (on=open, off=closed) and it's state can be toggled using current source base. But there is a third command STOP for which the current UI is not prepared. Maybe we can omit this one.
- **position opening** Setting the cover position in percentage cannot be done on current code base. Currently we are not processing the `cover position` parameter and for sure we'll need new UI page where this could be set. Not an easy task.
- **tilting** Will need same amount of work as **position opening**. Is anybody using this anyway?

As I see it, we could do the **simple open/close** as temporary solution and take this opportunity to develop `hasscontrol 2.0.0` with multiple screens. Currently there is only one universal "entity view screen" which displays all entities (light, switch, lock, script, scene, etc.). We should rewrite it in order to support multiple screens. This will enable us to add entities with different layouts like sensor (show value, no icon), cover (option to set position), ac (set temperature, cold/warm). And basically be prepared for future entities.

@karlenek what do you think?

**Comment by karlenek** [comment]
Adding simple open/close would not be too much effort. However, adding positioning and tilting would probably require some redesign.

I have had in my mind to further extend the functionality and add support for more entity specific functions, like setting the brightness on a light.

I agree that open/close could be added now, but the rest probably have to wait for 2.0 :)

**Comment by rforro** [comment]
@karlenek I would like to hear your ideas, can we switch to the email? Because Monkey C is bit new for me, I have some questions to the code base. It looks like to me that at the beginning the widget was build for scenes only and currently the other entities have to work inside this boundaries.

**Comment by karlenek** [comment]
You are correct, the widget was originally built for controlling scenes, since thats basically the only thing Im using it for. But as I started I expanded it to support some entities as well. 

Sure we can continue on email, or slack. I have created a workspace for HassControl, just not sure how to invite you without posting the link publicly here. As far as I know there are no ways to send a PM on github.

**Comment by PurelyNicole** [comment]
@karlenek Sorry for my late reply as well, I missed the GitHub notification. Open/Close would be enough for my particular use case. As what I'm hoping to do is open/close my garage door from my watch when on my bike.

**Comment by mb-software** [comment]
Hi and thanks for this great widget. 
Any news for cover entities? My garage door also is a cover entity, and open/close would be the only thing I need. But right now it's not possible using this widget. Earlier it was mentioned that a simple open/close function could be easily implemented also in V1.xx. Is this planned in the near future?

**Comment by pniewiadowski** [comment]
I am waiting for this functionality as well but in the mean time I created a workaround.
Instead of adding cover entity to widget, I have created simple Script to toggle cover entity.
This way you can open/close covers from within this widget, using Home Assistant Script.

```
toggle_covers:
  alias: Toggle covers
  sequence:
  - service: cover.toggle
    target:
      entity_id: cover.living_roller_shutters
  mode: single
```

**Comment by karlenek** [comment]
@mb-software, @pniewiadowski 

I can try to implement something quick during next week, like a simple toggle function. 🙂
I think it will take some time before version 2.0 rewrite is finished and can be released.
